\input texinfo

@c %**start of header
@setfilename SmartCalc.info
@settitle SmartCalc v.2.0 Manual
@c %**end of header

@copying
This is a manual for SmartCalc v.2.0

Copyright @copyright{} 2023 noisejaq
@end copying

@ifnottex
@node Top
@top The SmartCalc v.2.0 program. Description of work.

Краткое описание работы программы SmartCalc v.2.0 и её функционала.

@titlefont{Описание программы}

В проекте реализован калькулятор на языке программирования С++ с использованием @acronym{ООП}. @*
Логика программы реализована с использованием паттерна @acronym{MVC}.@*
Помимо базовых арифметических операций (плюс-минус и умножить-поделить), @*
калькулятор имеет возможность вычислять арифметические выражения с учетом приоритетов, @*
а так же некоторые математические функции (синус, косинус, логарифм и т.д.). @*
Помимо вычисления выражений калькулятор поддерживает использование переменной @i{x} @*
и построение графика соответствующей функции.


@titlefont{Описание функционала SmartCalc v2.0}

@itemize @bullet
@item
Программа разработана на языке С++ стандарта C++17 с использованием компилятора g++. 
@item
Код программы находится в папке src 
@item
Сборка программы настроена с помощью Makefile со стандартным набором целей для GNU-программ: 
all, install, uninstall, clean, dvi, dist, test, gcov_report. 
Установка производится в каталог SmartCalc_v2.0/src/build
@item
Программа разработана в соответствии с принципами @acronym{ООП}
@item
Обеспечено покрытие unit-тестами модулей, связанных с вычислением выражений, с помощью библиотеки GTest
@item
Графический пользовательский интерфейс реализован на базе Qt
@item
На вход программы могут подаваться как целые числа, так и вещественные числа, записанные через точку.
Реализована обработка чисел в экспаненциальной форме записи.
@item
Вычисление производится после полного ввода вычисляемого выражения и нажатия на символ `=`
@item
Вычисление произвольных скобочных арифметических выражений в инфиксной нотации
@item
Вычисление произвольных скобочных арифметических выражений в инфиксной нотации с подстановкой значения переменной @i{x} в виде числа
@item
Область определения и область значения функций ограничена числами от -1000000 до 1000000
@item
Максимальная длина вычисляемого выражения - 255 символов
@item
Построение графика функции, заданной с помощью выражения в инфиксной нотации с переменной @i{x} 
(с координатными осями, отметкой используемого масштаба и сеткой с адаптивным шагом)
@end itemize
@end ifnottex


@titlepage
@title SmartCalc v.2.0 Manual

@page
@vskip 0pt plus 1fill
@insertcopying
@end titlepage

@bye